### ISSUE TITLE
V. 0.6.2 Broke a lot of things

### ISSUE THREAD

**Issue by heywolf15** [rNeomy/auto-tab-discard#307]
Firefox 104.0.2
Only what I usually use
Discard inactive tabs after x time doesn't work
From toolbar and all context menu
- Discard Tabs to the left and right doesn't work
- Discard all other tabs doesn't work
- Can only discard tab, one by one
- Open in new discarded tab doesn't work
- Hotkeys doesn't work

**Comment by homlett** [comment]
I confirm the issues mentioned above. Also, existing discarded tabs are lost after FF restart:
```
File not found.
Firefox can’t find the file at moz-extension://...
```

**Comment by rNeomy** [comment]
> existing discarded tabs are lost after FF 

@homlett, This extension does not use locale pages to discard tabs. It uses the native method. Even if you remove the extension, you still have your discarded tabs. The page that you are referring must be a local page of another extension.

**Comment by imcraymond** [comment]
I'm on the FF beta channel and have the same issue. I see no errors in the about:debugging panel. I noticed yesterday the tab right-click menu item was missing. It did exist after restarting FF this morning, but I "think" running the reload command above got rid of it again. A subsequent restart brought it back. Disable/enable extension does not bring it back. It simply appears that the timer is not running in my limited experience, though I don't use the other features mentioned above.

**Comment by heywolf15** [comment]
I only got this
Reading manifest: Warning processing storage: An unexpected property was found in the WebExtension manifest.

**Comment by anpryl** [comment]
Evaluating `chrome.alarms.getAll(a => console.log(a))`
Result:
```
Uncaught TypeError: chrome.alarms is undefined
    <anonymous> debugger eval code:1
```

**Comment by anpryl** [comment]
It looks like `chrome.runtime.reload()` fixed issues for me.

**Comment by imcraymond** [comment]
At home I'm using 104.0.2 and see the same issue. I also see the manifest warning mentioned above, and the reload() removes the tab right click menu item. Makes me suspect a possible extension interference. Below is a copy/paste of above command.
chrome.alarms.getAll(a => console.log(a))
undefined
Array []
The array is rather expansive, poking around I didn't see anything that stood out to me.

**Comment by rNeomy** [comment]
It seems like the extension is not initiated correctly in the reports. Wait for the `0.6.3.1` release to pass the review and report back. Hopefully, the issue is fixed.

**Comment by Sada-Mio** [comment]
> What the output of the following in the inspect -> console tab:
> 
> ```js
> chrome.alarms.getAll(a => console.log(a))
> ```
> 
> Can you guys reproduce the issue on a clean profile? https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

Believe I found the conflicting extension:
 
- New clean FF profile
- Install Auto-tab-discard
- Install uBlock-Origin, change settings > default behavior > disable JavaScript
- unable to discard tabs in other window

Problem only occurs with Version 0.6.2, the older previous Version 0.5.0 works fine with uBlock

**Comment by heywolf15** [comment]
@Sada-Mio How to revert back to older version?

**Comment by EvPw** [comment]
It still is not working for me after the latest update. Extension still won't discard my tabs after a set time frame

**Comment by imcraymond** [comment]
FYI, with 0.6.3.1, things are mostly the same as above (e.g. manifest issue, etc.). On a good note doing the reload() does NOT remove the mouse right click menu option. Hopefully that is a clue.

**Comment by imcraymond** [comment]
Also just noticed, if I'm on one tab and  right mouse click and select "Discard Tab" on another tab, it appears to have been discarded (e.g. shows the icon). But when I return to that tab it is at it's previous state, it used to reload the page. Hope I explained that correctly.

**Comment by EvPw** [comment]
Update: Conducted further tests on ATD within Firefox hours ago, and it still doesn't automatically discard inactive tabs after a set time period

**Comment by rNeomy** [comment]
Unfortunately, I cannot reproduce the issue. 

https://user-images.githubusercontent.com/14104614/189809237-8a263742-53fb-4c07-ab3f-90e1c301c250.mp4

**Comment by rNeomy** [comment]
> Update: Conducted further tests on ATD within Firefox hours ago

How about? 

Discard inactive tabs after **1** minute when the number of inactive tabs exceeds **0**

**Comment by Sada-Mio** [comment]
> Unfortunately, I cannot reproduce the issue.

Seems it depends which website you have loaded with uBlock javascript disabled.

Example: _https://www.etsy.com_ for me always breaks "discard other tabs" on a fresh profile

**Comment by rNeomy** [comment]
@Sada-Mio any errors on the browser console (Ctrl + Shift + J)? How about `about:debugging#/runtime/this-firefox` -> Inspect -> Console?

**Comment by imcraymond** [comment]
I see a lot of the following, doesn't matter which tab I'm on:
TypeError: channel.loadInfo.loadingPrincipal is null
    matchRequest resource://devtools/server/actors/network-monitor/utils/network-utils.js:392
    _shouldIgnoreChannel resource://devtools/server/actors/network-monitor/network-observer.js:258
    _onRequestHeader resource://devtools/server/actors/network-monitor/network-observer.js:775
    observeActivity resource://devtools/server/actors/network-monitor/network-observer.js:660
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103

Also, reloading the Toolbox tab for this extension returns:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 chrome:508:24
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). chrome:62:22

**Comment by Wilkolicious** [comment]
Still not working for me on Firefox.  Reverted back to 0.5.0 and everything working again.

**Comment by Sada-Mio** [comment]
> @Sada-Mio any errors on the browser console (Ctrl + Shift + J)? How about `about:debugging#/runtime/this-firefox` -> Inspect -> Console?

![Annotation 2022-09-13 130835](https://user-images.githubusercontent.com/38301959/189999403-aa615464-3ae7-4db3-adf5-cb66427678ef.jpg)

**Comment by imcraymond** [comment]
I just noticed something curious. I had set it to "Discard inactive tabs after 1 minutes (zero to disable) when the number of inactive tabs exceeds 0" as mentioned previously. I always load a few Reddit pages early in the morning, today some servers were whacked and I didn't go to Reddit for a while.

It appeared that tabs were being discarded correctly, until I went to a Reddit page.

Below are the extensions I use for Reddit:
Old Reddit Redirect
Reddit (Au) Comment Highlights
Reddit Enhancement Suite

I still don't see anything in the Toolbox tab for Auto Tab Discard, but today the manifest warning I've always seen in the Debugging tab is gone. Neither Firefox or the add-on upgraded. There were a few other extensions that also showed that warning, they have also cleared up.

**Comment by imcraymond** [comment]
So I disabled the above add-ons, restarted Firefox and repeated with the same result. Not sure why old.reddit would cause issues, but I hope this helps.

**Comment by imcraymond** [comment]
Did some more experimentation. I use uBlock Origin with all the filters, after disabling uBlock Origin on old.reddit, things appear to be hibernating (though it does take a lot longer than 1 minute).

**Comment by Sada-Mio** [comment]
> Unfortunately, I cannot reproduce the issue.

@rNeomy did further testing on a clean profile with the top 100 US websites to see which sites are unable to discard with uBlock javascript disabled

Found the following could not:

- nytimes.com
- fandom.com
- force.com
- etsy.com
- zoom.us
- instacart.com
- linkedin.com
- codegrepper.com
- fiverr.com
- trello.com

Noticed a common pattern. Any website loaded with googletagmanager.com blocked would break discard via "discard all other tabs". Further more, also prevents other tabs from discarding. Discard function will work again closing the problematic tab. 

![Annotation 2022-09-14 161210](https://user-images.githubusercontent.com/38301959/190278796-b2cb5d2d-e505-4ced-ba32-458283350cdb.jpg)

**Comment by LeetHaxor** [comment]
Still not working on firefox. Have to use 0.5.0 to get it to work properly.

**Comment by re11ding** [comment]
I'm also having issues. Simply having ublock origin enabled seems to cause functionality to break for me.

**Comment by re11ding** [comment]
> Still not working on firefox. Have to use 0.5.0 to get it to work properly.

How are you downgrading? I'd like to as well to fix things for the time being.

**Comment by heywolf15** [comment]
@re11ding Go to the Firefox extension page, scroll down to the "More information", there's Version History click "See all versions", click download file on the version you want

**Comment by EvPw** [comment]
Update #2: The latest version of ATD now is working for me on Firefox

**Comment by rNeomy** [comment]
I think I found the issue. Can you guys give the developer version a try and let me know if it works for you or not?

1. Download https://github.com/rNeomy/auto-tab-discard/archive/refs/heads/master.zip
2. Extract to a local directory
3. Open "about:debugging#/runtime/this-firefox" in a browser tab
4. Use the "Load Temporary Add-on" button and point it to "v3 -> manifest.json"

**Comment by Ved-un** [comment]
Downloaded and again this

![flameshot_262](https://user-images.githubusercontent.com/48730277/190978357-7a5e917e-81da-4deb-8d66-08c347969bc5.png)

**Comment by imcraymond** [comment]
Appears to be working for me also, though I wish I disabled the original one first. Confused me for a bit.

I've noticed several add-ons with that manifest warning, so I suspect that is due to seeing a manifest v3 attribute and not worth looking at.

**Comment by Sada-Mio** [comment]
loaded "v3 -> manifest.json"

appears to be working. Previously site like etsy.com or nytimes.com would not discard, but now it does.

**Comment by EvPw** [comment]
I suspect it was due to the manifest warning

**Comment by heywolf15** [comment]
The developer version appears to be working on my end

**Comment by rNeomy** [comment]
Perfect! The new release (`0.6.3.2`) now includes the fix.

**Comment by heywolf15** [comment]
Sorry just another thing, "Open in new discarded tab" when you click the tab it will not automatically reload and need to be refreshed. But it's not a big deal, thank you.

**Comment by rNeomy** [comment]
> "Open in new discarded tab" when you click the tab it will not automatically reload

Will be fixed by the next release. Thanks for the report.

**Comment by imcraymond** [comment]
@rNeomy Thank you for working/fixing this. Sincerely appreciated.
